name: mecazone
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
#Sitching to Higher SDK
environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  connectivity_plus: ^3.0.6
  cupertino_icons: ^1.0.2
  dots_indicator: ^2.1.0
  dropdown_search: ^5.0.6
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  intl: any
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.2
  flutter_inappwebview: ^5.7.2+3
  flutter_local_notifications: ^14.1.1
  flutter_localization: ^0.1.11
  firebase_messaging: ^14.6.4
  flutter_secure_storage: ^8.0.0
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.5
  get: ^4.6.5
  get_storage: ^2.1.1
  http: 0.13.0
  image_picker: ^0.8.7+5
  logger: ^1.3.0
  modal_progress_hud_nsn:
  notification_permissions: ^0.6.1
  page_transition: ^2.0.9
  pinput: ^2.2.31
  shared_preferences: ^2.1.0
  smooth_page_indicator: ^1.1.0
  url_launcher: 
  webview_flutter: ^4.2.0
  flutter_screenutil:
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
    - lib/lang/

  fonts:
    - family: AppBold
      fonts:
        - asset: assets/fonts/font_bold.ttf
    - family: AppLight
      fonts:
        - asset: assets/fonts/font_light.ttf
    - family: AppRegular
      fonts:
        - asset: assets/fonts/font_regular.ttf
    - family: AppSemiBold
      fonts:
        - asset: assets/fonts/font_semibold.ttf